"""empty message

Revision ID: 4ab130439746
Revises: b5d0377bd27a
Create Date: 2021-03-11 20:35:00.703961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab130439746'
down_revision = 'b5d0377bd27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('stop_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('bike_id', sa.String(), nullable=True),
    sa.Column('from_station_id', sa.String(), nullable=True),
    sa.Column('from_station_name', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.String(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike3')
    # ### end Alembic commands ###
