"""empty message

Revision ID: dcc6586a4938
Revises: 6d6b0ca2c0c9
Create Date: 2021-03-11 20:04:39.107137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc6586a4938'
down_revision = '6d6b0ca2c0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('stop_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('bike_id', sa.String(), nullable=True),
    sa.Column('from_station_id', sa.String(), nullable=True),
    sa.Column('from_station_name', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.String(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike2')
    # ### end Alembic commands ###
